  _target_: uni2ts.data.builder.ConcatDatasetBuilder
  _args_:
    _target_: uni2ts.data.builder.simple.generate_eval_builders
    dataset: BizITObs-Service_eval
    offset: 6185
    eval_length: 884
    prediction_lengths:
      - 96
      - 192
      - 336
    context_lengths:
      - 512
    patch_sizes:
      - 64
      - 128
