_target_: uni2ts.data.builder.ConcatDatasetBuilder
_args_:
  _target_: uni2ts.data.builder.simple.generate_eval_builders
  dataset: ETTh1_eval
  offset: 11520
  eval_length: 2880
  prediction_lengths: [96, 192, 336]
  context_lengths: [512]
  patch_sizes: [32]