  _target_: uni2ts.data.builder.ConcatDatasetBuilder
  _args_:
    _target_: uni2ts.data.builder.simple.generate_eval_builders
    dataset: illness_eval
    offset: 676
    eval_length: 97
    prediction_lengths:
      - 24
      - 48
      - 60
    context_lengths:
      - 128
    patch_sizes:
      - 16
      - 32
