  _target_: uni2ts.data.builder.ConcatDatasetBuilder
  _args_:
    _target_: uni2ts.data.builder.simple.generate_eval_builders
    dataset: MSFT_w_eval
    offset: 1424
    eval_length: 203
    prediction_lengths:
      - 24
      - 48
      - 60
    context_lengths:
      - 128
    patch_sizes:
      - 16
      - 32
