  _target_: uni2ts.data.builder.ConcatDatasetBuilder
  _args_:
    _target_: uni2ts.data.builder.simple.generate_eval_builders
    dataset: NYCTAXI_Inflow_eval
    offset: 1529
    eval_length: 218
    prediction_lengths:
      - 24
      - 48
      - 60
    context_lengths:
      - 128
    patch_sizes:
      - 32
      - 64
