  _target_: uni2ts.data.builder.ConcatDatasetBuilder
  _args_:
    _target_: uni2ts.data.builder.simple.generate_eval_builders
    dataset: ZafNoo_eval
    offset: 13458
    eval_length: 1923
    prediction_lengths:
      - 96
      - 192
      - 336
    context_lengths:
      - 512
    patch_sizes:
      - 32
      - 64
      - 128
