training_data_paths:
- "/home/xiongshiwei/chronos-forecasting/data/Train/NYCTAXI_Outflow/data-00000-of-00001.arrow"
probability:
- 1.0
context_length: 128
per_device_train_batch_size: 16
model_id: amazon/chronos-t5-base