_target_: uni2ts.model.moirai.MoiraiForecast.load_from_checkpoint
checkpoint_path: /home/xiongshiwei/uni2ts/outputs/finetune/moirai_1.0_R_large/CzeLan/CzeLan/checkpoints/epoch=18-step=1900.ckpt
num_samples: 100
patch_size: 32
context_length: 512
