_target_: uni2ts.model.moirai.MoiraiForecast.load_from_checkpoint
checkpoint_path: /home/xiongshiwei/uni2ts/outputs/finetune/moirai_1.0_R_large/illness/illness/checkpoints/epoch=3-step=400.ckpt
num_samples: 100
patch_size: 32
context_length: 128
