_target_: uni2ts.model.moirai.MoiraiForecast.load_from_checkpoint
checkpoint_path: /home/xiongshiwei/uni2ts/outputs/finetune/moirai_1.0_R_large/NASDAQ_w/NASDAQ_w/checkpoints/epoch=6-step=700.ckpt
num_samples: 100
patch_size: 32
context_length: 128
