_target_: uni2ts.model.moirai.MoiraiForecast.load_from_checkpoint
checkpoint_path: /home/xiongshiwei/uni2ts/outputs/finetune/moirai_1.0_R_large/NYCTAXI_Inflow/NYCTAXI_Inflow/checkpoints/epoch=10-step=1100.ckpt
num_samples: 100
patch_size: 32
context_length: 128
