_target_: uni2ts.model.moirai.MoiraiForecast.load_from_checkpoint
checkpoint_path: /home/xiongshiwei/uni2ts/outputs/finetune/moirai_1.0_R_large/NYISO_AL/NYISO_AL/checkpoints/epoch=11-step=1200.ckpt
num_samples: 100
patch_size: 32
context_length: 512
